server:
  host: 0.0.0.0
  port: 8081

redis:
  host: redis
  port: 6379
  password: ""
  db: 0

storage:
  data_dir: ~/.agentainer/data

docker:
  host: unix:///var/run/docker.sock

security:
  default_token: agentainer-default-token

features:
  request_persistence: true