apiVersion: v1
kind: AgentDeployment
metadata:
  name: basic-agent-deployment
  description: Example deployment with multiple agent types
  labels:
    environment: development
    version: "1.0"

spec:
  agents:
    # Web service agent
    - name: web-service
      image: nginx:alpine
      replicas: 2
      env:
        NGINX_HOST: localhost
        NGINX_PORT: "80"
      resources:
        memory: 256M
        cpu: 0.5
      volumes:
        - host: ./data/web
          container: /usr/share/nginx/html
        - host: ./config/nginx.conf
          container: /etc/nginx/nginx.conf
          readOnly: true
      autoRestart: true

    # API service agent
    - name: api-service
      image: node:18-alpine
      env:
        NODE_ENV: production
        PORT: "3000"
      resources:
        memory: 512M
        cpu: 1
      volumes:
        - host: ./data/api
          container: /app/data
      autoRestart: true

    # Database agent
    - name: database
      image: postgres:15-alpine
      env:
        POSTGRES_PASSWORD: ${DB_PASSWORD:-defaultpass}
        POSTGRES_DB: agentainer
      resources:
        memory: 1G
        cpu: 2
      volumes:
        - host: ./data/postgres
          container: /var/lib/postgresql/data
      persistence:
        enabled: true