FROM python:3.9-slim

WORKDIR /app

# Install required packages
RUN pip install redis

# Copy the reducer script
COPY reducer.py .

# Set environment for the workflow
ENV PYTHONUNBUFFERED=1

CMD ["python", "reducer.py"]